version: "3"

services:
  blueocean:
    image: jenkinsci/blueocean
    container_name: jenkins-blueocean
    restart: always
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - 49000:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    links:
      - jenkins
    networks:
      jenkins-network:
        aliases:
          - docker
  jenkins:
    image: docker:dind
    container_name: jenkins-docker
    restart: always
    privileged: true
    ports:
      - 2376:2376
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - $HOME/jenkins/jenkins-data:/var/jenkins_home
    networks:
      jenkins-network:
        aliases:
          - docker
volumes:
  jenkins-docker-certs:
  jenkins-data:
networks:
  jenkins-network:
    driver: bridge
