version: '3'

services:
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_BASICAUTH_USERNAME: root
            ME_CONFIG_BASICAUTH_PASSWORD: admin
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
        links: 
            - mongo
        networks: 
            - mongo-compose-network
    mongo:
        image: mongo
        container_name: mongodb
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports: 
            - 27017:27017
        volumes: 
            - data:/data/db
        networks: 
            - mongo-compose-network
volumes:
    data:
networks: 
    mongo-compose-network:
        driver: bridge